### ISSUE TITLE
[Question] Using all this with Jira + Bitbucket

### ISSUE THREAD

**Issue by KristofKlein** [EducationPerfect/azure-jira-update#10]
Hi,

so I did my initial test with the scripts, and looks really nice. Now I was about to push this to my pipelines just to see it in action. But I think I have a problem here (like quite some others). And maybe you have an idea how to resolve that. 

So from my understanding looking at the script you ask the release pipeline for the changes, such that you can extract the Issue Numbers....the thing is: using Bitbucket (Cloud) is not capable to transport that information into Azure. SO checking for Issues, or Commits, it is actually always empty. 
![image](https://user-images.githubusercontent.com/23500845/160585687-a8587818-6d00-42fe-9f40-5bbfdf5a7b69.png)

Any Idea how to get that information via an alternative way?!

so we have Jira ABC-123-> Bitbucket [ABC-123_BanchName,CommitMsg: Ref_ABC-123] -> DevOps Ppielines (PR,CI) -> Release.

Or do I do something wrong with DevOps that it looses the Issues? 
Any Ideas is welcome :)

**Comment by mwheeler-ep** [comment]
We are limited by what DevOps provides. We've looked into parsing git branch differences but its just too fiddly to do in a general sense. Sorry
