### ISSUE TITLE
Could you provide more info on how to install in Azure Pipelines? 

### ISSUE THREAD

**Issue by DarthSonic** [EducationPerfect/azure-jira-update#11]
I am a little lost on how and where to install this in Azure Pipelines. Could you provide a step-by-step solution with screenshots?

**Comment by DarthSonic** [comment]
Also, how to send issues that are resolved within the release? How can I read the list of Jira keys to the issue that got resolved?

**Comment by mwheeler-ep** [comment]
A usage example is provided in the Readme.md https://github.com/EducationPerfect/azure-jira-update#pipeline-usage
The JIRA IDs are scrapped from the commits from the Azure DevOps changes API `$env:SYSTEM_COLLECTIONURI/$env:SYSTEM_TEAMPROJECT/_traceability/runview/changes?currentRunId=$($env:BUILD_BUILDID)&__rt=fps`

**Comment by DarthSonic** [comment]
@mwheeler-ep but where do I put that YAML file? I do not see any "custom yaml" option in Azure Releases.

**Comment by DarthSonic** [comment]
Would be really helpful to get step-by-step instruction where and how to setup in Azure DevOps. I would appreciate it very much.

**Comment by mwheeler-ep** [comment]
This is specifically for YAML pipelines (https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops). You might be able to get it to work with the Releases Pipeline GUI (eg whats displayed here https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)  but I wouldn't even know where to start with working that out. We don't really have the time to look into Release Pipeline GUI though as none of our deployments use and we don't intend to use it.

A full example of using it as a YAML pipeline is here https://github.com/EducationPerfect/azure-jira-update/blob/main/example.yml - this would be in your build repo and you create a pipeline that points at this yaml file to run it.

**Comment by DarthSonic** [comment]
Okay. Is it possible to add Cmdlet "Add-JiraDeploymentInformation" to my Release Pipeline? How can I access that within Azure Powershell?

**Comment by mwheeler-ep** [comment]
I'm not sure sorry. You'll have to work that out yourself
