### ISSUE TITLE
Cannot convert value "1648551970,87108" to type "System.Int32". Error: "Input string was not in a correct format."

### ISSUE THREAD

**Issue by KristofKlein** [EducationPerfect/azure-jira-update#9]
Hi ! I had this issue:
_Cannot convert value "1648551970,87108" to type "System.Int32". Error: "Input string was not in a correct format."_

when calling _Add-JiraDeploymentInformation_ in a local powershell session.

turned out to be this line in the code:
`
updateSequenceNumber     = (Get-Date -UFormat "%s");
`
I changed it to:
`updateSequenceNumber     = [math]::Round((Get-Date -UFormat "%s"));
`

not sure if this is a local setting that makes it that strange none int number.
Also in term of the readme that says " you can call this locally" - there is also 
`deploymentSequenceNumber = [Int]($env:BUILD_BUILDID);
`
that actually is a pipeline parameter and should look different :) 

Using Win10, Powershell 5.1

Apart from that! So happy you made this! So sad that MS didn't manage to integrate with Jira AND Bitbucket correctly with their extensions.

**Comment by mwheeler-ep** [comment]
ah, our build agents run much newer version of powershell where this isn't an issue
